移动到页面上的下一个交互元素

移动到页面上的下一个交互元素
#这些是支持的融资模式平台
github：#替换为最多 4 you you you you you you you you you，（user1，user2）
Patreon：#用单个 Patreon你
Open_Collective:#用单个 Collective you
Ko_fi：#替换为单个 Ko-fi你
Tidelift：#替换为单个 Tidelift you you-you/-you，you，npm/babel
Community_Bridge:#替换为单个 Community you you you you，cloud-foundry
Liberapay：#替换为单个 Liberapay you
issuehunt：#替换为单个 issuehunt你
LFX_拥挤：#替换为单个 LFX you-mayou-，mayou，cloud-foundry
Polar：#用单个 Polar*
给我买一杯咖啡
